//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElTonioloAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidos
    {
        public int id { get; set; }
        public int id_pedido { get; set; }
        public int id_cliente { get; set; }
        public Nullable<int> id_entregador { get; set; }
        public bool processamento { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
